# Generated by Django 4.2.9 on 2024-01-10 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_date_crated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='date_crated',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_category', to='auctions.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img_url',
            field=models.CharField(max_length=1000, verbose_name='img_url'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=30, verbose_name='title'),
        ),
    ]
