# Generated by Django 4.2.9 on 2024-01-13 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
    ]
