# Generated by Django 4.2.9 on 2024-01-15 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_bid_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
